### ISSUE TITLE
Error on search

### ISSUE THREAD

**Issue by maacl** [daschwa/helm-itunes#2]
I get the following error when trying to search:

nil
 "2014-06-04 23:16:41.083 osascript[82464:1107] Cannot find executable for CFBundle 0x7fc9e9d3d760 </Library/ScriptingAdditions/AeroFSFinderExtension.osax> (not loaded)
osascript: OpenScripting.framework - scripting addition \"/Library/ScriptingAdditions/AeroFSFinderExtension.osax\" declares no loadable handlers.
306:307: syntax error: Expected “,” but found unknown token. (-2741)
" - nil

iTunes Search
nil
 "2014-06-04 23:16:41.154 osascript[82466:1107] Cannot find executable for CFBundle 0x7fde5bd14c90 </Library/ScriptingAdditions/AeroFSFinderExtension.osax> (not loaded)
osascript: OpenScripting.framework - scripting addition \"/Library/ScriptingAdditions/AeroFSFinderExtension.osax\" declares no loadable handlers.
306:307: syntax error: Expected “,” but found unknown token. (-2741)
" - nil

iTunes Search
nil
 "2014-06-04 23:16:41.221 osascript[82468:1107] Cannot find executable for CFBundle 0x7fdba9e1e5d0 </Library/ScriptingAdditions/AeroFSFinderExtension.osax> (not loaded)
osascript: OpenScripting.framework - scripting addition \"/Library/ScriptingAdditions/AeroFSFinderExtension.osax\" declares no loadable handlers.
306:307: syntax error: Expected “,” but found unknown token. (-2741)
" - nil

iTunes Search
nil
 "2014-06-04 23:16:41.293 osascript[82470:1107] Cannot find executable for CFBundle 0x7fe5706410b0 </Library/ScriptingAdditions/AeroFSFinderExtension.osax> (not loaded)
osascript: OpenScripting.framework - scripting addition \"/Library/ScriptingAdditions/AeroFSFinderExtension.osax\" declares no loadable handlers.
306:307: syntax error: Expected “,” but found unknown token. (-2741)
" - nil

**Comment by maacl** [comment]
Removing /Library/ScriptingAdditions/AeroFSFinderExtension.osax now fixes this on OS X Yosemite.

**Comment by daschwa** [comment]
Wow, excellent. Amazing detective work and commitment. I'm sorry I never could help more.
